### ISSUE TITLE
Can't install qtnetwork from overlay

### ISSUE THREAD

**Issue by MAH69IK** [gentoo/libressl#289]
Hello!
I've tried to install qtnetwork from this overlay but can't do this. emerge doesn't use overlay.
I install layman then `layman -a libressl`.

`equery y qtnetwork`:
```
5.11.1 | o + ~ ~ o + + + ~ o o o ~ ~ o o | 6 o 5/5.11 | gentoo
5.11.3 | o + ~ ~ o ~ + + ~ o o o ~ ~ o o | 6 o        | gentoo
```

`emerge --info --verbose | less`:
```
...
gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://mirror.yandex.ru/gentoo-portage/
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts:
    sync-rsync-verify-max-age: 24

libressl
    location: /var/lib/layman/libressl
    masters: gentoo
    priority: 50
...
```

`emerge -pv qtnetwork`:
```
[ebuild  N     ] dev-libs/openssl-1.0.2q::gentoo  USE="asm sctp sslv3 tls-heartbeat zlib -bindist -gmp -kerberos -rfc3779 -sslv2 -static-libs -test -vanilla" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="(sse2)" 5 233 KiB
[ebuild  N     ] dev-qt/qtnetwork-5.11.3:5/5.11::gentoo  USE="ssl -bindist -connman -debug -libproxy -networkmanager -test" 0 KiB
[blocks B      ] dev-libs/openssl:0 ("dev-libs/openssl:0" is blocking dev-libs/libressl-2.6.5)
```

What wrong with my system? Why I can't install qtnetwork from libressl repo?
